#!/bin/sh -eu

. $(dirname $0)/../core/runner.sh

banner Doing work
#################


s3=$(unique_s3_url file)
s3_foo=$(unique_s3_url foo)
s3_bar=$(unique_s3_url bar)

echo "blah" > ${TEST}/file
echo "meh" > ${TEST}/file2

$MISMI upload ${TEST}/file2 $s3 || exit_cleanup $?
if $MISMI upload ${TEST}/file $s3; then echo "Was allowed to upload twice"; exit_cleanup 1; fi
$MISMI upload --overwrite ${TEST}/file $s3 || exit_cleanup $?
$MISMI download $s3 ${TEST}/download || exit_cleanup $?

if diff -q ${TEST}/file ${TEST}/download; then
    echo "PASSED [upload / downlaod]"
else
    echo ""
    echo "Test case [upload / download] failed."
    exit_cleanup
fi

$MISMI upload ${TEST}/file $s3_foo || exit_cleanup $?
$MISMI download $s3_foo ${TEST}/. || exit_cleanup $?

if [ -f ${TEST}/foo ]; then
    echo "PASSED [downlaod to dot]"
else
    echo ""
    echo "Test case [download to dot] failed."
    exit_cleanup
fi

$MISMI upload ${TEST}/file $s3_bar || exit_cleanup $?
$MISMI download $s3_bar ${TEST}/ || exit_cleanup $?

if [ -f ${TEST}/bar ]; then
    echo "PASSED [downlaod to dir]"
else
    echo ""
    echo "Test case [download to dir] failed."
    exit_cleanup
fi

$MISMI delete $s3 || exit_cleanup $?
$MISMI delete $s3_foo || exit_cleanup $?
$MISMI delete $s3_bar || exit_cleanup $?

$MISMI write $s3 "foobar" || exit_cleanup $?

$MISMI write $s3 "nofoobar" --overwrite || exit_cleanup $?

$MISMI read $s3 > ${TEST}/read || exit_cleanup $?

if [ "nofoobar" = $(cat ${TEST}/read) ]; then
    echo "PASSED [write / overwrite / read]"
else
    echo ""
    echo "Test case [write / overwrite / read] failed."
    exit_cleanup
fi

if [ $($MISMI cat $s3) = $(cat ${TEST}/read) ]; then
    echo "PASSED [stream]"
else
    echo ""
    echo "Test case [stream] failed."
    exit_cleanup
fi

foo=$(unique_s3_url foo)
$MISMI copy $s3 $foo || exit_cleanup $?

if $MISMI exists $s3 && $MISMI exists $foo; then
    echo "PASSED [copy]"
else
    echo ""
    echo "Test case [copy] failed."
    exit_cleanup
fi

bar=$(unique_s3_url bar)
$MISMI move $s3 $bar || exit_cleanup $?

if ! $MISMI exists $s3 && $MISMI exists $bar; then
    echo "PASSED [move]"
else
    echo ""
    echo "Test case [move] failed."
    exit_cleanup
fi

$MISMI size $bar > ${TEST}/size || exit_cleanup $?

if find ${TEST}/file -size $(cat ${TEST}/size); then
    echo "PASSED [size]"
else
    echo ""
    echo "Test case [size] failed."
    exit_cleanup
fi

cleanup
